#!/usr/bin/bash

 function-get-password(){
 

    clear

    #To recive the password from user for first time !
    echo "Enetr Password : "
    stty -echo
    read password1
    clear

    #To confirm the password and check.
    echo "Please re-enter your password : "
    stty -echo
    read password2
    clear

    #To check the passwords
    if [[ $password1 -ne $password2 ]];then

        echo "Password dose not match !"
        exit 1

    else

        echo "Your password is : $password1 "      
        exit 0  

    fi
 }
        


